require('dotenv').config();
const express=require('express');
const cors=require('cors');
const auth=require('./routes/auth');
const products=require('./routes/products');
const stock=require('./routes/stock');
const suppliers=require('./routes/suppliers');
const warehouses=require('./routes/warehouses');
const purchaseOrders=require('./routes/purchaseOrders');
const dashboard=require('./routes/dashboard');
const reports=require('./routes/reports');
const {notFound,errorHandler}=require('./middleware/error');
const app=express();
app.use(cors({origin:process.env.CLIENT_URL?.split(',')||true}));
app.use(express.json({limit:'1mb'}));
app.get('/api/health',(req,res)=>res.json({status:'ok',service:'smart-inventory-api'}));
app.use('/api/auth',auth);
app.use('/api/products',products);
app.use('/api/stock',stock);
app.use('/api/suppliers',suppliers);
app.use('/api/warehouses',warehouses);
app.use('/api/purchase-orders',purchaseOrders);
app.use('/api/dashboard',dashboard);
app.use('/api/reports',reports);
app.use(notFound);
app.use(errorHandler);
module.exports=app;